var text = [
"Esti o femeie puternica",
"Spiritul tau e invincibil",
"Meriti o marire la fel de mult ca el",
"E o perioada grozava sa fii femeie",
"Ignoranta e mai rea decat promiscuitatea",
"Anul asta poate face el curat de Paste",
"Nu faci pe desteapta. Esti desteapta.",
"Nu te mai compara cu alte femei. Tu esti tu.",
"Zdrobim patriarhatul anul asta?",
"N-ai nevoie de un barbat ca sa fii intreaga",
"Daca nu ai chef, nu trebuie sa gatesti",
"Nu inseamna nu. Foloseste-l mai des",
"Feminismul e pentru toata lumea",
"Menstruatia nu este o pedeapsa divina",
"Corpul tau, regulile tale",
"Opinia lor nu te defineste",
"Cand ascultam niste Patti Smith impreuna?",
"Nu iti chinui corpul doar ca sa fii acceptata",
"Alimenteaza-te cu niste Girl powerrr",
"Nu, n-ai nicio vina pentru ce-a facut Eva",
"Sexul frumos? Nu multumesc.",
"Sexul slab? Niciodata.",
"Sustine femeile care te inspira",
"Remediul pentru saracie este emanciparea femeii",
"Esti la fel de fragila ca orgoliul masculin",
];
